using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

/// <summary>
/// One menu command that produces the whole playable game from an empty project.
/// </summary>
public static class DroneBuildSetup
{
    [MenuItem("Tools/Drone Strike/BUILD EVERYTHING", priority = -100)]
    public static void BuildEverything()
    {
        InputSettingsSetup.UseLegacyInput();

        DroneMaterials.Generate();
        MissionBuilder.BuildAll();
        MainMenuBuilder.BuildScene();
        ApplyBuildSettings();

        if (!InputSettingsSetup.IsLegacyInputEnabled())
        {
            Debug.LogError("Drone Strike: the scenes are built, but input handling still has to be "
                           + "switched. Set Edit > Project Settings > Player > Active Input Handling "
                           + "to \"Both\" and restart Unity.");
            return;
        }

        Debug.Log("Drone Strike: project ready. Open Assets/Scenes/MainMenu.unity and press Play. "
                  + "If input was just switched, restart Unity first.");
    }

    [MenuItem("Tools/Drone Strike/3 - Apply Build Settings")]
    public static void ApplyBuildSettings()
    {
        // The menu is first, so it is what the player lands on. The mission
        // scenes follow in the order the catalogue lists them — a scene the
        // menu can name but the build does not contain fails at the moment the
        // player presses the button, which is the worst place to find out.
        var scenes = new List<EditorBuildSettingsScene>
        {
            new EditorBuildSettingsScene("Assets/Scenes/MainMenu.unity", true)
        };

        foreach (MissionMap map in MissionCatalog.Maps)
            scenes.Add(new EditorBuildSettingsScene("Assets/Scenes/" + map.sceneName + ".unity", true));

        EditorBuildSettings.scenes = scenes.ToArray();

        // The single-map build saved its scene under a different name. Left
        // behind it is a scene the menu cannot reach and the build does not
        // ship, whose MissionManager has no launch pads — opening it by mistake
        // looks like the game is broken. It was generated by this tool, so this
        // tool clears it up.
        const string retired = "Assets/Scenes/IndustrialZone.unity";
        if (AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(retired) != null)
        {
            AssetDatabase.DeleteAsset(retired);
            Debug.Log("Drone Strike: removed the retired scene " + retired + ".");
        }

        // Yandex Games serves the plain uncompressed WebGL layout most reliably.
        PlayerSettings.WebGL.compressionFormat = WebGLCompressionFormat.Disabled;
        PlayerSettings.runInBackground = true;

        // Unity's stock template centres a fixed-size canvas and draws a logo
        // footer under it. Yandex requirement 1.6.2.1 wants the play area to
        // reach the edge of the space the platform gives it, and the first
        // draft upload came back framed in white with a Unity bar along the
        // bottom. Assets/WebGLTemplates/YandexGames is the same markup Unity
        // generates, with the canvas stretched and the footer dropped.
        PlayerSettings.WebGL.template = "PROJECT:YandexGames";

        Debug.Log("Drone Strike: build settings applied — " + scenes.Count
                  + " scenes, WebGL, compression off, Yandex template.");
    }
}
